[[redirects]]
from = "/proxy/*"
to = "https://api.cinewall.shop"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18.20.5"
